### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by SaiUpadhyayula** [leantechstacks/jcart-microservices#1]
Hey Siva,

Very nice idea to create this project for collaberative learning. Have you already started creating the initial project setup ?

A week ago I started a similar project https://github.com/SaiUpadhyayula/MicroShopper but I did not do anything concrete, apart from adding Spring Cloud. 

I would love to take part in this project.

Sai

**Comment by sivaprasadreddy** [comment]
Hi Sai,
I have just started thinking about what are all services need to be created and where to start.
In a couple of days I will add more details to project wiki and we can start.

If you want to chat/talk about it please send me chat invitation to sivaprasadreddy.k@gmail.com.

Thanks for showing interest in this collaborative learning.

Siva
